# Generated by Django 3.2.8 on 2021-10-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
