# Generated by Django 3.2.8 on 2021-10-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('Process', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
