# Generated by Django 3.2.8 on 2021-10-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_process'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='Process',
            new_name='process_id',
        ),
    ]
