# Generated by Django 3.2.8 on 2021-11-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_rename_process_process_process_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default=None, upload_to='images/')),
            ],
        ),
    ]
