# Generated by Django 3.2.8 on 2021-11-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_metauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='metauser',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
