# Generated by Django 3.2.8 on 2021-11-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_metauser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metauser',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
