# Generated by Django 3.2.8 on 2021-11-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20211125_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default=None, null=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
