# Generated by Django 3.2.8 on 2021-11-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20211125_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metauser',
            name='image',
            field=models.ImageField(default='default.png', null=True, upload_to='images/'),
        ),
    ]
